name: "Benchmark contract"
on:
  - push

jobs:
  analysis:
    name: "Gas usage analysis"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: make install_solc_linux
      - name: Compile contract file
        run: make build_cbor
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-03-31
          override: true
      - name: Test WASM on Rust VM
        run: |
          cd testing
          rustup target add wasm32-unknown-unknown
          RUST_BACKTRACE=1 cargo r